### ISSUE TITLE
Floating pets above bottom bar

### ISSUE THREAD

**Issue by octoshrimpy** [blairjordan/codachi#7]
It would be sweet if pets could appear without a panel. I know the power mode plugin found a way to overlay over the editor itself, so there is a chance it may be possible. 

If its been longer than 24h and i havent posted the relevant source code for power mode, ping me please!

**Comment by blairjordan** [comment]
Thanks for posting this Issue!

From https://github.com/hoovercj/vscode-power-mode#known-issues:

> this extension relies on using TextEditorDecorations to set css properties for ranges in the editor.

I wonder if it's possible to hijack this to display our characters. It seems like an incredibly hacky approach, but maybe not impossible to achieve ...

**Comment by octoshrimpy** [comment]
Looking at the fancy particles like rift, it looks like it's using an animation,so the hijacking is totally possible. 

also looking at the combo meter here https://github.com/hoovercj/vscode-power-mode/blob/master/src/combo/editor-combo-meter.ts

---

okay, after playing around some more:

```css
footer#workbench\.parts\.statusbar:before {
    content: "";
    height: 4rem;
    position: fixed;
    bottom: 21px;
    width: 4rem;
    left: 20rem;
    display: inline-block;
    z-index: 999;
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAepJREFUWIXtlrFrGlEcxz+KgwGx59hJKwEHlxCO0AaypWAnCWaRQocgHW5xzZ8QSJYsGYokhA4uWUoHCy1ZBAV5JEKxVAhWJ8l0KkJChphB3nm5GHxn6pDW7/Tu+979fr/34/v73sEcc8wxx/8Oj+rBWEQf2J/rTeFxck7Um2JifK9qAQBlI0TZCD3gzoWf4p9Ti8st+ZVj+twUUCtdAaAFwsQiDLRAmFrpkjgL+EihBcIAFC/asylAovChB4SAHrXSiP/68wjfbopayctxdYYFyE4AxFcXRsF2U/f2VOBKA7OA0hTEIvpgZTsNgB4diTD9dnPs+fz3E0TDpLKTnzgJz6cD0yaY1AFXRiTHbG/x0uIz1WtyS35LjG8OTF7o7+iKgpIRuZqC4fhBNrjBfu8bADngU2LD0kbZyJMNalSEWkxXBSQqrwGIrQ/X7z++QgRN9GiI5YNDAD4bW9AwlWNO5QPjcGZsIRomOlD/0VF+T3kK6k3h6YoCnt+/LE40TCuZXAsXt4cpRSiR5HHPP+7f/H0ROhOvLY5vYPHiVjmWsg/IT2ymev1gXwuESdLmCy/p9FsW1+m3/hEnhPtu6NSCE7ILKhpQLsBeiGw5DMVmLypJW1mA8EQfsCeSf0huMVUH5Np+y8f4SbgD6fm4RxTzZgcAAAAASUVORK5CYII=);
    /* transform: scale(5); */
    background-repeat: no-repeat;
    background-size: cover;
    image-rendering: pixelated;
    pointer-events: none;
}
``` 

it can totally be done without injecting any elements into thepage, and instead styling a `:before` on the footer! 

![walkin](https://user-images.githubusercontent.com/7097172/199334337-a5bdf28d-a377-4467-a732-3da25fd7c1a9.gif)
